export const doctors = [
  {
    id: 1,
    name: "Dr. Anita Dewi",
    specialty: "Psikiater",
    rating: 4.9,
    reviews: 134,
    experience: "14 tahun",
    location: "Mental Wellness Center, Jakarta",
    image: "/image/image.png",
    availability: [
      { day: "Senin", slots: ["13:00", "14:00", "15:00"] },
      { day: "Rabu", slots: ["09:00", "10:00", "11:00"] },
      { day: "Jumat", slots: ["14:00", "15:00"] },
    ],
    price: "Rp 450.000",
  },
  {
    id: 2,
    name: "Dr. Reza Pratama",
    specialty: "Psikolog Klinis",
    rating: 4.8,
    reviews: 120,
    experience: "10 tahun",
    location: "Klinik Sehat Jiwa, Bandung",
    image: "/image/image.png",
    availability: [
      { day: "Selasa", slots: ["10:00", "11:00", "14:00"] },
      { day: "Kamis", slots: ["09:00", "10:00"] },
      { day: "Sabtu", slots: ["11:00", "12:00"] },
    ],
    price: "Rp 400.000",
  },
  {
    id: 3,
    name: "Dr. Intan Maharani",
    specialty: "Psikolog Anak & Remaja",
    rating: 4.9,
    reviews: 98,
    experience: "8 tahun",
    location: "Ruang Peduli, Yogyakarta",
    image: "/image/image.png",
    availability: [
      { day: "Senin", slots: ["09:00", "10:00", "11:00"] },
      { day: "Rabu", slots: ["13:00", "14:00"] },
      { day: "Jumat", slots: ["09:00", "10:00"] },
    ],
    price: "Rp 375.000",
  },
  {
    id: 4,
    name: "Dr. Andi Saputra",
    specialty: "Konselor Pernikahan & Keluarga",
    rating: 4.7,
    reviews: 89,
    experience: "12 tahun",
    location: "Konseling Harmoni, Surabaya",
    image: "/image/image.png",
    availability: [
      { day: "Selasa", slots: ["13:00", "14:00", "15:00"] },
      { day: "Kamis", slots: ["10:00", "11:00", "12:00"] },
    ],
    price: "Rp 350.000",
  },
  {
    id: 5,
    name: "Dr. Maya Lestari",
    specialty: "Psikolog Dewasa",
    rating: 4.8,
    reviews: 110,
    experience: "11 tahun",
    location: "MindCare Center, Jakarta",
    image: "/image/image.png",
    availability: [
      { day: "Senin", slots: ["10:00", "11:00"] },
      { day: "Rabu", slots: ["14:00", "15:00", "16:00"] },
      { day: "Sabtu", slots: ["09:00", "10:00"] },
    ],
    price: "Rp 390.000",
  },
  {
    id: 6,
    name: "Dr. Dimas Nugroho",
    specialty: "Psikolog Klinis",
    rating: 4.9,
    reviews: 145,
    experience: "13 tahun",
    location: "Ruang Aman, Malang",
    image: "/image/image.png",
    availability: [
      { day: "Selasa", slots: ["09:00", "10:00"] },
      { day: "Kamis", slots: ["13:00", "14:00"] },
      { day: "Sabtu", slots: ["10:00", "11:00", "12:00"] },
    ],
    price: "Rp 420.000",
  },
];

export const specialties = [
  "Semua Spesialis",
  "Psikiater",
  "Psikolog Klinis",
  "Psikolog Anak & Remaja",
  "Psikolog Dewasa",
  "Konselor Pernikahan & Keluarga",
];

export const categories = [
  { value: "rating", label: "Rating Tertinggi" },
  { value: "experience", label: "Pengalaman Terbanyak" },
  { value: "price", label: "Harga Terendah" },
];